name: Track Developer Activities

on:
  issues:
    types: [opened, assigned, unassigned, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  Track-Activity:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4

      # Get details of the event that triggered the workflow and generate comment about it
      - name: Generate Comment 
        id: generate-comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const generateComment = require('./github-actions/trigger-issue/track-developer-activities/generate-comment.js');
            return await generateComment(context);

      # Post generated comment on the prework issue of the developer who triggered the workflow 
      - name: Post Comment on Prework
        id: post-comment-on-prework
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const postIssueComment = require('./github-actions/utils/post-issue-comment.js');
            const comment = ${{ steps.generate-comment.outputs.result }};
            return await postIssueComment(comment, github, context)
